#include "foo/ping_lib.h"

#include "aos/events/simulated_event_loop.h"
#include "aos/testing/path.h"
#include "gtest/gtest.h"

namespace aos::testing {

namespace chrono = std::chrono;

class PingPongTest : public ::testing::Test {
 public:
  PingPongTest()
      // Using ArtifactPath to account for the file structure in the Bazel test
      // environment, read the AOS config generated by aos_config bazel rule
      // (note how the name of this config file is identical to the name of the
      // aos_config rule, not to the name of the hand-written file.
      : config_(aos::configuration::ReadConfig(
            ArtifactPath("foo/pingpong_config.json"))),
        // Construct a SimulatedEventLoopFactory according to the config. This
        // factory will handle coordinating the simulation.
        event_loop_factory_(&config_.message()),
        // Actually create the EventLoop that the Ping application will use. We
        // pass in a name that should match the name that is used in the AOS
        // config (although doesn't strictly have to).
        ping_event_loop_(event_loop_factory_.MakeEventLoop("ping")),
        ping_(ping_event_loop_.get()),
        // Create a separate "test" EventLoop (the name doesn't typically
        // matter) which will be used for interacting with the Ping application.
        test_event_loop_(event_loop_factory_.MakeEventLoop("test")) {}

  // Config and factory.
  // The factory creates connected event loops.  Each application needs
  // a separate event loop (because you can't send a message to yourself in a
  // single event loop).  The created event loops can then send messages to each
  // other and trigger callbacks to be called, or fetchers to receive data.
  aos::FlatbufferDetachedBuffer<aos::Configuration> config_;
  SimulatedEventLoopFactory event_loop_factory_;

  // Event loop and application for Ping.
  std::unique_ptr<EventLoop> ping_event_loop_;
  Ping ping_;

  // Event loop for running our tests.
  std::unique_ptr<EventLoop> test_event_loop_;
};

// Tests that the ping application sends a bunch of pings with unique counters.
TEST_F(PingPongTest, SendsPings) {
  // We keep this test relatively straightforward--we just check that the Ping
  // application is sending out Ping messages with counters that continually
  // increment by one. In order to do this, we use the test EventLoop that we
  // craeted to create a Watcher on the appropriate channel and check each Ping
  // message as it comes in.
  int last_count = 0;
  test_event_loop_->MakeWatcher(
      "/test", [&last_count](const aos::examples::Ping &ping) {
        EXPECT_EQ(ping.value(), last_count + 1)
            << "Count was expected to increment by exactly 1.";
        last_count = ping.value();
      });
  // RunFor runs all the EventLoop's in the factory simulataneously,
  // coordinating events and messages on all the channels.
  event_loop_factory_.RunFor(chrono::seconds(10));
  // At the end, ensure that we actually got Ping messages--if we don't test
  // this, then we could end up never receiving *any* messages and the rest of
  // the test would pass.
  EXPECT_LT(0, last_count) << "Expected at least 1 Ping message.";
}
}  // namespace aos::testing